In [8]:
import networkx as nx
import numpy as np
from pgmpy.models.BayesianModel import BayesianModel
from pgmpy.factors.discrete import TabularCPD
from pgmpy.factors.discrete import State
import random as random

In [2]:
student = BayesianModel([('diff', 'grade'), ('intel', 'grade')])
cpd_d = TabularCPD('diff', 2, [[0.6], [0.4]])
cpd_i = TabularCPD('intel', 2, [[0.7], [0.3]])
cpd_g = TabularCPD('grade', 3, [[0.3, 0.05, 0.9, 0.5], 
                                [0.4, 0.25,0.08, 0.3], 
                                [0.3, 0.7, 0.02, 0.2]],
               ['intel', 'diff'], [2, 2])
student.add_cpds(cpd_d, cpd_i, cpd_g)

In [61]:
cpd_g.variables

['grade', 'intel', 'diff']

In [3]:
model = student
sorted_order = list(nx.topological_sort(student))
sorted_order

['intel', 'diff', 'grade']

In [5]:
sample_count = 3
types = [(var_name, 'int') for var_name in sorted_order]
sampled = np.zeros(sample_count, dtype=types).view(np.recarray)

In [51]:
sampled[0]

0

In [12]:
len(cpd.variables)

3

In [84]:
variable_count = len(cpd.variables)
size = sample_count * variable_count
print(size)
r = [random.random() for _ in range(size)]
r[0]

9


0.5079978060487877

In [90]:
k = 0
for node in sorted_order:
            cpd = model.get_cpds(node)
            print(cpd)
            #print((cpd.values))
            #print(cpa.variables)
            evidence = cpd.variables[:0:-1]
            print(evidence)
            
            if evidence:
                #
                pass
            else:
                # no evidence case
                print('no evd')
                print(get_value_from_cpd(cpd.values,r[k]))
            
            k+=1
                

╒═════════╤═════╕
│ intel_0 │ 0.7 │
├─────────┼─────┤
│ intel_1 │ 0.3 │
╘═════════╧═════╛
[]
no evd
0
╒════════╤═════╕
│ diff_0 │ 0.6 │
├────────┼─────┤
│ diff_1 │ 0.4 │
╘════════╧═════╛
[]
no evd
1
╒═════════╤═════════╤═════════╤═════════╤═════════╕
│ intel   │ intel_0 │ intel_0 │ intel_1 │ intel_1 │
├─────────┼─────────┼─────────┼─────────┼─────────┤
│ diff    │ diff_0  │ diff_1  │ diff_0  │ diff_1  │
├─────────┼─────────┼─────────┼─────────┼─────────┤
│ grade_0 │ 0.3     │ 0.05    │ 0.9     │ 0.5     │
├─────────┼─────────┼─────────┼─────────┼─────────┤
│ grade_1 │ 0.4     │ 0.25    │ 0.08    │ 0.3     │
├─────────┼─────────┼─────────┼─────────┼─────────┤
│ grade_2 │ 0.3     │ 0.7     │ 0.02    │ 0.2     │
╘═════════╧═════════╧═════════╧═════════╧═════════╛
['diff', 'intel']


In [45]:

def get_value_from_cpd(cpd_values,random_value):
    cpd_value_line = []
    current = 0;
    for i,cpd_value in enumerate(cpd_values):
        current += cpd_value
        if random_value<= current:
            return i
        
    '''
    for i,cpd_value in enumerate(cpd_values):
        #print(i)
        if value<=cpd_value
        
    '''

In [80]:
p = [0.7,0.3]
get_value_from_cpd(p,0.8)

1

In [71]:
cpd_g.values

array([[[0.3 , 0.05],
        [0.9 , 0.5 ]],

       [[0.4 , 0.25],
        [0.08, 0.3 ]],

       [[0.3 , 0.7 ],
        [0.02, 0.2 ]]])

In [70]:
cpd_g.values[0]

array([[0.3 , 0.05],
       [0.9 , 0.5 ]])

In [74]:
x = cpd_g.values
x

array([[[0.3 , 0.05],
        [0.9 , 0.5 ]],

       [[0.4 , 0.25],
        [0.08, 0.3 ]],

       [[0.3 , 0.7 ],
        [0.02, 0.2 ]]])

#1

In [96]:
x[0][0][0]

0.3

In [97]:
x[1][0][0]

0.4

In [98]:
x[2][0][0]

0.3

#2

In [106]:
x[0][0][1]

0.05

In [107]:
x[1][0][1]

0.25

In [108]:
x[2][0][1]

0.7

In [113]:
len(x[0][0])

2

In [127]:
k_length = len(x)
j_lenght = len(x[0])
i_lenght = len(x[0][0])
for i in range(i_lenght):
    for j in range(j_lenght):
        for k in range(k_length):
            v = x[k][i][j]
            #print(v)
        

In [130]:
def get_value_from_cpd_evidence(cpd_values):
    k_length = len(x)
    j_lenght = len(x[0])
    i_lenght = len(x[0][0])
    for i in range(i_lenght):
        for j in range(j_lenght):
            for k in range(k_length):
                v = x[k][i][j]
                print(v)

In [131]:
get_value_from_cpd_evidence(cpd_g.values)

0.3
0.4
0.3
0.05
0.25
0.7
0.9
0.08
0.02
0.5
0.3
0.2


In [133]:
def get_value_from_cpd_evidence(cpd_values,evidence):
    k_length = len(x)
    for k in range(k_length):
        v = x[k][evidence[0]][evidence[1]]
        print(v)

In [136]:
get_value_from_cpd_evidence(cpd_g.values,[1,1])

0.5
0.3
0.2
